import 'package:tech_blog_app_3/gen/assets.gen.dart';

import 'data_models.dart';

Map homePagePosterMap = {
  "imageAsset": Assets.images.poster.path,
  "writer": "نویسنده",
  "date": "یک روز پیش",
  "title": "دوازده قدم برنامه نویسی یک دوره ",
  "view": "251",
};

// blog fake data
List<HashTagModel> tagList = [
  HashTagModel(title: "جاوا"),
  HashTagModel(title: "کاتلین"),
  HashTagModel(title: "برنامه نویسی وب"),
  HashTagModel(title: "هوش مصنوعی"),
  HashTagModel(title: "iot"),
  HashTagModel(title: "دارت"),
  HashTagModel(title: "پادکست رادیو کدیاد"),
];

List<BlogModel> blogList = [
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
  BlogModel(
    id: 1,
    imageUrl: "",
    title: "",
    writer: "",
    writerImageUrl: "",
    date: "",
    content: "",
    views: "",
  ),
];
